Add --harmony flag to let Koa start properly
When trying to run the docs app with `npm start`, this error happens: 

    ...flummox/docs/node_modules/koa/lib/application.js:179
    function *respond(next) {
         ^
    SyntaxError: Unexpected token *

This seems to be caused by Koa needing the harmony flag. 
Issue: https://github.com/koajs/koa/issues/179
As stated here too:  https://github.com/koajs/koa#installation